CREATE TABLE IF NOT EXISTS t_p18469490_vision_2024.users (
  id SERIAL PRIMARY KEY,
  nick VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);